file_format: "1"
id: sparklite
name: sparklite
type: shield
url: https://github.com/badjeff/sparklite/
requires: [pro_micro]
exposes: []
features:
  - keys
siblings:
  - sparklite_left
  - sparklite_right
