##### Created using Keymap Drawer (https://keymap-drawer.streamlit.app/)
layout:
  ortho_layout:
    split: true
    rows: 2
    columns: 5
    thumbs: 2
layers:
  ALP:
    # left upper five (0.0 - 0.4)
    - { t: "", h: "", type: ghost }
    - { t: "w", h: "CTL" }
    - { t: "e", h: "" }
    - { t: "r", h: "ALT" }
    - { t: "", h: "", type: ghost }
    # right upper five (0.5 - 0.9)
    - { t: "", h: "", type: ghost }
    - { t: "u", h: "ALT" }
    - { t: "i", h: "" }
    - { t: "o", h: "CTL" }
    - { t: "", h: "", type: ghost }
    # left home five (1.0 - 1.4)
    - { t: "a", h: "SHFT" }
    - { t: "s", h: "NUM" }
    - { t: "d", h: "NAV" }
    - { t: "f", h: "GUI" }
    - { t: "", h: "", type: ghost }
    # right home five (1.5 - 1.9)
    - { t: "", h: "", type: ghost }
    - { t: "j", h: "GUI" }
    - { t: "k", h: "NAV" }
    - { t: "l", h: "NUM" }
    - { t: ";:", h: "SHFT" }
    # thumbs
    - { t: "ESC", h: "LGUI" }
    - { t: "TAB", h: "LCTRL" }
    - { t: "ENTER", h: "RALT" }
    - { t: "SPC", h: "NAV" }

  NAV:
    # left upper five (0.0 - 0.4)
    - { t: "", h: "", type: ghost }
    - { t: "RCLK", h: "" }
    - { t: "MCLK", h: "" }
    - { t: "LCLK", h: "" }
    - { t: "", h: "", type: ghost }
    # right upper five (0.5 - 0.9)
    - { t: "", h: "", type: ghost }
    - { t: "M-DN", h: "" }
    - { t: "M-UP", h: "" }
    - { t: "M-RT", h: "" }
    - { t: "", h: "", type: ghost }
    # left home five (1.0 - 1.4)
    - { t: "`~", h: "SHFT" }
    - { t: "MB4", h: "" }
    - { t: "[{", h: "", type: held }
    - { t: "]}", h: "" }
    - { t: "", h: "", type: ghost }
    # right home five (1.5 - 1.9)
    - { t: "", h: "", type: ghost }
    - { t: "↓", h: "" }
    - { t: "↑", h: "", type: held }
    - { t: "→", h: "" }
    - { t: "/?", h: "SHFT" }
    # thumbs
    - { t: "trans", h: "" }
    - { t: "trans", h: "" }
    - { t: "trans", h: "" }
    - { t: "trans", h: "" }

  NUM:
    # left upper five (0.0 - 0.4)
    - { t: "", h: "", type: ghost }
    - { t: "4$", h: "" }
    - { t: "5%", h: "" }
    - { t: "6^", h: "" }
    - { t: "", h: "", type: ghost }
    # right upper five (0.5 - 0.9)
    - { t: "", h: "", type: ghost }
    - { t: "7&", h: "" }
    - { t: "8*", h: "" }
    - { t: "9(", h: "" }
    - { t: "", h: "", type: ghost }
    # left home five (1.0 - 1.4)
    - { t: "`~", h: "SHFT" }
    - { t: "1$", h: "", type: held }
    - { t: "2%", h: "" }
    - { t: "3^", h: "" }
    - { t: "", h: "", type: ghost }
    # right home five (1.5 - 1.9)
    - { t: "", h: "", type: ghost }
    - { t: "-_", h: "" }
    - { t: "+=", h: "" }
    - { t: "\\|", h: "", type: held }
    - { t: "0)", h: "SHFT" }
    # thumbs=
    - { t: "trans", h: "" }
    - { t: "trans", h: "" }
    - { t: "trans", h: "" }
    - { t: "trans", h: "" }

  MED:
    # left upper five (0.0 - 0.4)
    - { t: "", h: "", type: ghost }
    - { t: "BT0", h: "" }
    - { t: "BT1", h: "" }
    - { t: "BTCLR", h: "" }
    - { t: "", h: "", type: ghost }
    # right upper five (0.5 - 0.9)
    - { t: "", h: "", type: ghost }
    - { t: "", h: "" }
    - { t: "VOL_D", h: "" }
    - { t: "VOL_U", h: "" }
    - { t: "", h: "", type: ghost }
    # left home five (1.0 - 1.4)
    - { t: "", h: "" }
    - { t: "", h: "" }
    - { t: "", h: "" }
    - { t: "DFU", h: "" }
    - { t: "", h: "", type: ghost }
    # right home five (1.5 - 1.9)
    - { t: "", h: "", type: ghost }
    - { t: "DFU", h: "" }
    - { t: "BRI_D", h: "" }
    - { t: "BRI_U", h: "" }
    - { t: "", h: "" }
    # thumbs
    - { t: "ALP", h: "" }
    - { t: "", h: "" }
    - { t: "", h: "" }
    - { t: "", h: "" }

  FUN:
    # left upper five (0.0 - 0.4)
    - { t: "", h: "", type: ghost }
    - { t: "F4", h: "" }
    - { t: "F5", h: "" }
    - { t: "F6", h: "" }
    - { t: "", h: "", type: ghost }
    # right upper five (0.5 - 0.9)
    - { t: "", h: "", type: ghost }
    - { t: "F7", h: "" }
    - { t: "F8", h: "" }
    - { t: "F9", h: "" }
    - { t: "", h: "", type: ghost }
    # left home five (1.0 - 1.4)
    - { t: "", h: "" }
    - { t: "F1", h: "" }
    - { t: "F2", h: "" }
    - { t: "F3", h: "" }
    - { t: "", h: "", type: ghost }
    # right home five (1.5 - 1.9)
    - { t: "", h: "", type: ghost }
    - { t: "F10", h: "" }
    - { t: "F11", h: "" }
    - { t: "F12", h: "" }
    - { t: "", h: "" }
    # thumbs=
    - { t: "ALP", h: "" }
    - { t: "", h: "" }
    - { t: "", h: "" }
    - { t: "", h: "" }

combos:
  # Alpha
  - { p: [1, 2], k: "q", layers: [ALP] }
  - { p: [2, 3], k: "t", layers: [ALP] }
  - { p: [12, 13], k: "g", layers: [ALP] }
  - { p: [2, 13], k: "b", offset: 0.3, layers: [ALP] }

  - { p: [10, 20], k: "z", a: left, layers: [ALP] }
  - { p: [11, 20], k: "x", a: bottom, offset: 0.8, layers: [ALP] }
  - { p: [12, 20], k: "c", a: bottom, offset: 0.3, layers: [ALP] }
  - { p: [13, 20], k: "v", a: right, layers: [ALP] }
  - { p: [13, 21], k: "b", a: right, offset: -0.1, layers: [ALP] }

  - { p: [7, 8], k: "p", layers: [ALP] }
  - { p: [6, 7], k: "y", layers: [ALP] }
  - { p: [16, 17], k: "h", layers: [ALP] }
  - { p: [7, 16], k: "n", layers: [ALP] }

  - { p: [16, 23], k: "m", a: left, layers: [ALP] }
  - { p: [17, 23], k: ",<", a: bottom, offset: 0.3, layers: [ALP] }
  - { p: [18, 23], k: ".>", a: bottom, offset: 0.8, layers: [ALP] }
  - { p: [19, 23], k: "/?", a: right, layers: [ALP] }
  - { p: [16, 22], k: "n", a: left, offset: -0.1, layers: [ALP] }

  - { p: [17, 18], k: "BSPC", layers: [ALP] }
  - { p: [11, 12], k: "TAB", layers: [ALP] }

  # Navigation
  - { p: [16, 17], k: "←", layers: [NAV] }
  - { p: [6, 7], k: "M-LT", a: top, layers: [NAV] }

  # Media
  - { p: [6, 8], k: "FUN", a: top, layers: [NUM] }
  - { p: [16, 18], k: "MED", a: bottom, layers: [NUM] }

# this goes into the "configuration" code/text box at the bottom of the website!
draw_config:
  append_colon_to_layer_header: true
  arc_radius: 6.0
  arc_scale: 1.0
  combo_h: 26.0
  combo_w: 28.0
  inner_pad_h: 2.0
  inner_pad_w: 2.0
  key_h: 56.0
  key_rx: 6.0
  key_ry: 6.0
  key_w: 60.0
  line_spacing: 1.2
  outer_pad_h: 56.0
  outer_pad_w: 30.0
  small_pad: 5.0
  split_gap: 30.0
  svg_style: |
    /* font and background color specifications */
    svg {
        font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 14px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: #24292e;
    }

    /* default key styling */
    rect {
        fill: #f6f8fa;
        stroke: #c9cccf;
        stroke-width: 1;
    }

    /* color accent for combo boxes */
    rect.combo {
        fill: #cdf;
    }

    /* color accent for held keys */
    rect.held, rect.combo.held {
        fill: #fdd;
    }

    /* color accent for ghost (optional) keys */
    rect.ghost, rect.combo.ghost {
        fill: #fff0;
        stroke-width: 0;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    /* styling for layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        stroke: white;
        stroke-width: 2;
        paint-order: stroke;
    }

    /* styling for combo tap, and key hold/shifted label text */
    text.combo, text.hold, text.shifted {
        font-size: 11px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
    }

    /* styling for hold/shifted label text in combo box */
    text.combo.hold, text.combo.shifted {
        font-size: 8px;
    }

    /* styling for combo dendrons */
    path {
        stroke-width: 1;
        stroke: gray;
        fill: none;
    }